### ISSUE TITLE
internal/main/run_main_module.js:17:47 code: 'MODULE_NOT_FOUND',

### ISSUE THREAD

**Issue by jmoreno127** [plotly/dash-component-boilerplate#114]
Hi!

I am getting this error following the tutorial:

```
Hash: 2f30a0133b3ea5344684
Version: webpack 4.36.1
Time: 2434ms
Built at: 12/21/2020 1:39:28 PM
         Asset      Size  Chunks             Chunk Names
    web.min.js  3.15 KiB       0  [emitted]  main
web.min.js.map  7.41 KiB       0  [emitted]  main
Entrypoint main = web.min.js web.min.js.map
[0] external "PropTypes" 42 bytes {0} [built]
[1] external "React" 42 bytes {0} [built]
[2] ./src/lib/index.js + 1 modules 5.14 KiB {0} [built]
    | ./src/lib/index.js 146 bytes [built]
    |     + 1 hidden module
Executing: venv/bin/python -m dash.development.component_generator ./src/lib/components web -p package-info.json --jl-prefix '' --r-prefix ''
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/Users/jonathanmorenon/OneDrive/Freelance/Data'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Error generating metadata in web (status=1)
post_gen_project command failed: venv/bin/python -m dash.development.component_generator ./src/lib/components web -p package-info.json --jl-prefix '' --r-prefix ''
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```

I am on a Mac computer with Node v14.15.3, npm 6.14.9, and Python 3.7.6. Also getting the same error with a PC with node V12.10.0, npm 6.10.3, and python 3.8.3.

**Comment by malihassan20** [comment]
@jmoreno127 are you able to resolve this issue as I am getting the same error on my end?

**Comment by jmoreno127** [comment]
> @jmoreno127 are you able to resolve this issue as I am getting the same error on my end?

No, Ali. I have not been able to. There is no enough information on the internet, according to my research.

**Comment by xhlulu** [comment]
@malihassan20 thanks for reporting this! Are you following [this tutorial](https://dash.plotly.com/react-for-python-developers)? If so, which section caused the error?

There's a known issue with the npm scripts being outdated, and I submitted to a PR to correct it on dash-docs. The following scripts:
```
npm run build:js
npm run build:js-dev
npm run build:py
npm run build:all
```
have been replaced with those:
```
npm run build:js
npm run build:py_and_r
npm run build
```

(js-dev was removed).

**Comment by jmoreno127** [comment]
Thanks for your answer @xhlulu! Indeed, I am following that [tutorial](https://dash.plotly.com/react-for-python-developers). 

The error is generated when executing that line: `cookiecutter https://github.com/plotly/dash-component-boilerplate.git`

Everything looks fine until the following line:

Executing: npm run build:js

**Comment by malihassan20** [comment]
@xhlulu yes I am following the same tutorial. The error occurs same as above which @jmoreno127 have mentioned

**Comment by xhlulu** [comment]
@malihassan20 @jmoreno127 Can you upgrade dash with 
```
pip install dash --upgrade
```

**Comment by xhlulu** [comment]
I use it all the time inside WSL 2.0 and Ubuntu 20.04 with varying versions of Python and didn't run into that error. So I tried running it with a Windows 10 machine and the following configs:
```
Python 3.9
pip 20.2.3
npm 6.14.10 
node v14.15.4
```

I entered the following options:
![tempsnip](https://user-images.githubusercontent.com/21180505/108001521-a6ebbf00-6fba-11eb-9504-4d999fff2b7c.png)

All the python packages were installed correctly:
![image](https://user-images.githubusercontent.com/21180505/108001643-fcc06700-6fba-11eb-9069-f41f3ea33d86.png)

`npm install` worked as intended:
![image](https://user-images.githubusercontent.com/21180505/108001667-15308180-6fbb-11eb-8748-7e6ffd34a82d.png)

`npm run build:js` also didn't throw any error:
![image](https://user-images.githubusercontent.com/21180505/108001691-27aabb00-6fbb-11eb-807d-ec4b11f9895d.png)


@jmoreno127 @malihassan20 Here's a few more things you can try:
* Can you upgrade node, npm, and pip, and cookiecutter?
* Can you make sure to select True for creating venv, and to not leave any field blank (very important)?
* If you are using Windows, can you try to run it inside WSL 2.0?

If none of the above worked, can you paste the entire output of your console?

**Comment by jmoreno127** [comment]
@xhlulu Thank you for your answer!

I am still getting the error.

I am trying to configure it on macOS Big Sur Versio 11.2.1. I am using:

Python 3.7.6
pip 21.0.1
Cookiecutter 1.7.2
npm@6.14.9
node@v14.15.5

The error on the console is:

`Executing: npm run build:js

> my_own@0.0.1 build:js /Users/jonathanmorenon/OneDrive/Freelance/Data Enigma/D3/dash-react-tutorial/my_own
> webpack --mode production

Hash: 3f4c84016d8a280949d6
Version: webpack 4.36.1
Time: 2804ms
Built at: 02/18/2021 12:55:33 PM
            Asset      Size  Chunks             Chunk Names
    my_own.min.js  3.15 KiB       0  [emitted]  main
my_own.min.js.map  7.34 KiB       0  [emitted]  main
Entrypoint main = my_own.min.js my_own.min.js.map
[0] external "PropTypes" 42 bytes {0} [built]
[1] external "React" 42 bytes {0} [built]
[2] ./src/lib/index.js + 1 modules 5 KiB {0} [built]
    | ./src/lib/index.js 113 bytes [built]
    |     + 1 hidden module
Executing: venv/bin/python -m dash.development.component_generator ./src/lib/components my_own -p package-info.json --jl-prefix '' --r-prefix ''
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/Users/jonathanmorenon/OneDrive/Freelance/Data'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Error generating metadata in my_own (status=1)
post_gen_project command failed: venv/bin/python -m dash.development.component_generator ./src/lib/components my_own -p package-info.json --jl-prefix '' --r-prefix ''
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)`

![image](https://user-images.githubusercontent.com/26529160/108424040-a5163b80-7206-11eb-8b6a-6f0b7250f494.png)

**Comment by xhlulu** [comment]
Can you change your path? Might be that the component generator CLI doesn't like spaces in the path name. Might try:
```
cd Users/jonathanmorenon/
mkdir dash_apps
cd dash_apps
cookiecutter gh:plotly/dash-component-boilerplate
```

**Comment by jmoreno127** [comment]
That's exactly right! @xhlulu It finally worked! It was for the reason you have mentioned. Thank you so much!

**Comment by xhlulu** [comment]
@jmoreno127 Great to hear this!

@malihassan20 Can you confirm you have the same issue?

**Comment by Hazernit** [comment]
![image](https://user-images.githubusercontent.com/40500293/168448431-f1960b9d-ed85-42fb-9c37-4f35b8394661.png)
![image](https://user-images.githubusercontent.com/40500293/168448466-2c90bc22-9817-44ab-ab28-6f9409683ebd.png)
![image](https://user-images.githubusercontent.com/40500293/168448474-e1a5c903-5bfc-4398-89a8-544538a328c6.png)
Good evening, can you tell me what the problem might be? I tried to install Angular and got the following errors
