### ISSUE TITLE
Renaming "build:py_and_r" to "build:dash"?

### ISSUE THREAD

**Issue by xhlulu** [plotly/dash-component-boilerplate#116]
I wondering if that name would make more sense since `build:py_and_r` also generates the julia files.

**Comment by alexcjohnson** [comment]
Good call, we should update this. `build:dash` is a bit ambiguous though - in the core we call this [`build:backends`](https://github.com/plotly/dash-core-components/blob/cf2604812ce5c55c2971d77b22cff83bf70815b8/package.json#L32), shall we standardize on that?

**Comment by xhlulu** [comment]
I think it's a good idea to standardize. I guess backend works although it might be a bit harder to grasp for beginners (but should be easily to explain in the `dash-docs`).

Also should we keep `build:py_and_r` or remove it? I know removing `npm run build:all` has caused a little bit of friction, but might be mainly due to the mismatch in the `dash-docs` and the webinar.
