### ISSUE TITLE
TypeError: Cannot read property 'properties' of undefined

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/dash-component-boilerplate#12]
Walking through the README from top to bottom, I hit an error with `npm run build:js-dev`:

```

> my-dash-component@0.0.1 build:js-dev /Users/nicolas/plotly/dash-component-boilerplate
> webpack --mode development

/Users/nicolas/plotly/dash-component-boilerplate/node_modules/webpack-cli/bin/config-yargs.js:89
                                describe: optionsSchema.definitions.output.properties.path.description,
                                                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (/Users/nicolas/plotly/dash-component-boilerplate/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at /Users/nicolas/plotly/dash-component-boilerplate/node_modules/webpack-cli/bin/webpack.js:60:27
    at Object.<anonymous> (/Users/nicolas/plotly/dash-component-boilerplate/node_modules/webpack-cli/bin/webpack.js:515:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-dash-component@0.0.1 build:js-dev: `webpack --mode development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-dash-component@0.0.1 build:js-dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nicolas/.npm/_logs/2018-09-26T19_27_29_669Z-debug.log
```

**Comment by fskpf** [comment]
This was broken by a webpack update, see https://github.com/webpack/webpack/issues/8082

A workaround for now is to update both, webpack and webpack-cli in package.json:
```
    "webpack": "^4.20.2",
    "webpack-cli": "^3.1.1",
```

**Comment by nicolaskruchten** [comment]
That fixed it for me, thanks! @T4rk1n you want a PR?

**Comment by T4rk1n** [comment]
@nicolaskruchten  I got my cookiecutter PR coming up, I already changed the versions there.

**Comment by thomasoss** [comment]
That fixed it to me, too. ;-)
After altering the version von webpack in package.json and
npm install --save webpack-cli
the problem was fixed
Thank's

**Comment by syd192** [comment]
卸载再重装就好了~
npm uninstall webpack-cli
npm install webpack-cli

**Comment by sravani123** [comment]
>     "webpack": "^4.20.2",
>     "webpack-cli": "^3.1.1",

This worked well 👍

**Comment by jpthirumalai** [comment]
npm install --save webpack-cli -- fixed the error

**Comment by lucasverissimopapini** [comment]
> Isso foi quebrado por uma atualização do webpack, veja [webpack/webpack#8082](https://github.com/webpack/webpack/issues/8082)
> 
> Uma solução alternativa por enquanto é atualizar ambos, webpack e webpack-cli em package.json:
> 
> ```
>     "webpack": "^4.20.2",
>     "webpack-cli": "^3.1.1",
> ```

Isso super me ajudou e corrigiu o problema

**Comment by Praveenkj** [comment]
**TypeError: Cannot read property 'tapAsync' of undefined**

I am getting this after changed the webpack version.... Someone with me?!
