### ISSUE TITLE
Update package.json and update webpack to enable directly building async components

### ISSUE THREAD

**Issue by xhlulu** [plotly/dash-component-boilerplate#122]
Originally mentioned by @jdamiba 

I think that would be beneficial since there's a lot of change needed inside `webpack.config.js` and `package.json`, which not everyone would be familiar with.

This way, we'd simply need to import and use React.Suspense and use webpackChunkName without having to copy paste from dash-core-components and :knife: afterwards

**Comment by jdamiba** [comment]
Let's set up two one hour meetings and knock this out together with some pair programming. 

In the first meeting we will update the component boilerplate generator, and in the second we will update the dash-docs with info about async. 

I'm good most days except Tuesday.

**Comment by jackparmer** [comment]
@jdamiba @xhlulu can you please add @SL8onC to this pair program as well? Sebastian has React/Redux training and is learning Python/Dash - this looks like a nice opportunity to ride shotgun and ask some questions about creating custom Dash components.

**Comment by xhlulu** [comment]
of course! @SL8onC I added you to calendar invite
