### ISSUE TITLE
Warning: React does not recognize the `setProps` prop

### ISSUE THREAD

**Issue by jrneal1** [plotly/dash-component-boilerplate#131]
When testing my component within the boilerplate with usage.py, my component works correctly yielding no warnings.  However, when I build out the component via
`python setup.py sdist bdist_wheel`
followed by installing the created package in my Dash app, I get this warning:

`react-dom@16.v2_0_0m1630930951.14.0.js:82 Warning: React does not recognize the `setProps` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `setprops` instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

**Comment by T4rk1n** [comment]
You passed `setProps` somewhere in your code to an html element, probably by doing something like `<div {...props}>`
