### ISSUE TITLE
Problems to start project

### ISSUE THREAD

**Issue by fernandorozas** [plotly/dash-component-boilerplate#135]
I'm new to creating dash components in react.
After following the steps to create the component (https://dash.plotly.com/react-for-python-developers), when I try to run the project (npm start), I get the error:
  ERROR in multi ./src/demo/index.js webpack-plugin-serve/client
  Module not found: Error: Can't resolve 'webpack-plugin-serve/client'
How to fix?

step by step:
![image](https://user-images.githubusercontent.com/39917636/142662986-a176950d-3ac8-400e-9e52-5fa4f14f35ad.png)

**Comment by jlfsjunior** [comment]
Hi!

Have you fixed it already? I believe you haven't installed the dependencies yet (`npm install` from the project directory).

**Comment by fernandorozas** [comment]
Hi Jose.
I performed the installation of dependencies, and the error persists. I changed the approach and now I'm building the dashboard in react with the plotly.js library.

**Comment by glaserL** [comment]
Hey, I have the same error message. 
I sucessfully ran `npm install` and then used `npm start` but with `--port 9000` but I guess that shouldn't change anything?

**Comment by fernandorozas** [comment]
> Hey, I have the same error message. I sucessfully ran `npm install` and then used `npm start` but with `--port 9000` but I guess that shouldn't change anything?

Hi. Changing the port worked normally, although there is nothing running on the 5555.

**Comment by fernandorozas** [comment]
> Hey, I have the same error message. I sucessfully ran `npm install` and then used `npm start` but with `--port 9000` but I guess that shouldn't change anything?

Thanks
