### ISSUE TITLE
Do i need dash[dev]?

### ISSUE THREAD

**Issue by TheBubblePopped** [plotly/dash-component-boilerplate#147]
Hi there,

do i need dash[dev] or will just dash be sufficient for all tasks?

**Comment by T4rk1n** [comment]
You need `dash[dev]` installed.

**Comment by TheBubblePopped** [comment]
But why? In which step is the dev package required?

**Comment by T4rk1n** [comment]
The dev dependencies install these extra packages:
```
# Dependencies used for development new Dash components
coloredlogs>=15.0.1
fire>=0.4.0
PyYAML>=5.4.1
```

`fire` and `coloredlogs` are used internally for building the official packages, `PyYAML` is used in the component generator for the `R` package.

**Comment by TheBubblePopped** [comment]
Thank you for the swift response. I ran cookiecutter without dash[dev] just dash. Does that mean i have to redo the whole process and move my components there or am i set if i just pip install dash[dev] and run ```npm run build```?
