### ISSUE TITLE
Move extract-meta into its own NPM module

### ISSUE THREAD

**Issue by wilzbach** [plotly/dash-component-boilerplate#17]
It would be great if the entire meta-generation pipeline would be separated in its own package, s.t. upgrade to future versions of `dash-component-boilerplate` will be as easy as bumping the version number. 

In other words, I think at least `extract-meta` should be shipped as a package and not be part of the boilerplate. This would also make the pipeline more future proof in case you will change/improve the `extract-meta` script.

A more radical script would be to move in the direction of `react-scripts` which also abstracts away most of the configuration (like e.g. the webpack configuration - https://github.com/facebook/create-react-app/tree/master/packages/react-scripts/config) and thus allows them to ship new pipeline improvements to all users.
This is sth. that due to the ever-growing complexity of JS build tools (hello Babel 7) the majority of the user base really likes.

**Comment by T4rk1n** [comment]
Agreed, with #14 I changed a bit the `extract-meta` script to include a validation step and added another script to validate the components assets. They could be refactored in a `dash-components-scripts` package that can be installed in all the components repo so they can get updates.

**Comment by rmarren1** [comment]
+1 for this, updating the test `metadata.json` for `dash` was a bit hacky because this script isn't in its own package.
