### ISSUE TITLE
react and react-dom should be in dev-dependencies

### ISSUE THREAD

**Issue by bpostlethwaite** [plotly/dash-component-boilerplate#39]
react and react-dom are supplied by `dash-renderer`.

Also we need to update our Component Author documentation to make this clear (in case it isn't).

**Comment by T4rk1n** [comment]
It's in peer dependencies.

**Comment by nicolaskruchten** [comment]
it's also in dependencies, but it shouldn't be :)

**Comment by bpostlethwaite** [comment]
added note in dash-docs to include information about this for component authors https://github.com/plotly/dash-docs/issues/227#issuecomment-438271930
