### ISSUE TITLE
Option to use "-" for repo name

### ISSUE THREAD

**Issue by xhlulu** [plotly/dash-component-boilerplate#54]
At the moment, the project shortname is forced to be `dash_component`. However, writing `dash-component` for the repository name is pretty usually (e.g. `dash-core-components`), but currently the option is not given for the cookiecutter. It would be a nice addition.

**Comment by T4rk1n** [comment]
The `project_shortname` has to be `_` instead of `-` because it is both the project name and the python package name. We could decouple them into different variables allowing for any character for the project name.

**Comment by xhlulu** [comment]
That would be really nice!
