### ISSUE TITLE
missing quotes around property?

### ISSUE THREAD

**Issue by roeap** [plotly/dash-component-boilerplate#67]
Hi,
I may be wrong, but do think, that there should be quotes around `exceptions` in the following line. Or more specifically, my linter does ...

https://github.com/plotly/dash-component-boilerplate/blob/78e0028fbdedad27022dae6f7f06aee317cc1014/%7B%7Bcookiecutter.project_shortname%7D%7D/.eslintrc#L107

**Comment by alexcjohnson** [comment]
Good catch, thanks! -> #68
