### ISSUE TITLE
web shell Component

### ISSUE THREAD

**Issue by pheman** [plotly/dash-component-boilerplate#69]
I'm developing an data platform with dash which helps me a lot to build the interactive UI. However, I haven't found a web shell component implemented using dash framework.  

A web shell is very useful when the users want to do some bash command just like the console in jupyter environment. 

So, is there anyone who have some experience or information related?  Any information is appreciated.  Thanks

**Comment by chriddyp** [comment]
nothing that i’m aware of beyond just a textarea and a button. 
i’d recommend asking on the community forum: community.plot.ly/c/dash

**Comment by pheman** [comment]
Hi @chriddyp  , here I mean an interactive terminal/console. A textarea may be not the best choice.

**Comment by byronz** [comment]
@pheman  this might be the component you are looking for, https://github.com/nitin42/terminal-in-react. and you are definitely welcome to use this boilerplate project to build your first dash component and help our community to grow. as Chris mentioned, the best discussion place is our dash community website. thank you

**Comment by pheman** [comment]
thanks!@byronz
