### ISSUE TITLE
Issue with executing dash-component-boilerplate on Windows

### ISSUE THREAD

**Issue by Aprilhuu** [plotly/dash-component-boilerplate#74]
Hi I am trying to use dash-component-boilerplate to create a new project with python 2.7 and Anaconda on Windows. However, after using the command cookiecutter https://github.com/plotly/dash-component-boilerplate.git and entering attributes as suggested on the home page, it always fails with error messages shown below. I did not change anything during the process and just let the program to run on its own. I have tried on different computers, and the result is the same. I tried to search online but no one had the some issue as mine. Could someone help me take a look? Thank you so much.

My node version is 10.16.0, npm version is 6.9.0 and webpack version is 4.34.0

Following is the entire log:

`(py2) C:\Users\zianhu\PycharmProjects>cookiecutter dash-component-boilerplate
project_name [my dash component]:
project_shortname [my_dash_component]:
component_name [mydashcomponent]:
author_name [Enter your name (For package.json)]: April
author_email [Enter your email (For package.json)]: april.hu@icloud.com
description [Project Description]: hh
Select license:
1 - MIT License
2 - BSD License
3 - ISC License
4 - Apache Software License 2.0
5 - GNU General Public License v3
6 - Not open source
Choose from 1, 2, 3, 4, 5, 6 (1, 2, 3, 4, 5, 6) [1]: 6
publish_on_npm [True]:
install_dependencies [True]:
Executing: virtualenv venv
  No LICENSE.txt / LICENSE found in source
New python executable in C:\Users\zianhu\PycharmProjects\my_dash_component\venv\Scripts\python.exe
Installing setuptools, pip, wheel...
done.

Installing dependencies

Executing: venv\Scripts\python -m pip install -r requirements.txt
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting dash>=0.38.0 (from -r requirements.txt (line 2))
Collecting lxml (from dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/ef/e2/1968eb678147ef6bb6ef780d317f6eb25ea87bd427bcce1098c251f5461f/lxml-4.3.4-cp27-cp27m-win_amd64.whl
Collecting pytest-sugar (from dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/da/3b/f1e3c8830860c1df8f0e0f6713932475141210cfa021e362ca2774d2bf02/pytest_sugar-0.9.2-py2.py3-none-any.whl
Collecting waitress (from dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/41/e0/366785e4b9b4d212df4c3b084153bf7f5e5ab355928f5465144e5fc98494/waitress-1.3.0-py2.py3-none-any.whl
Collecting beautifulsoup4 (from dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/8b/0e/048a2f88bc4be5e3697df9dc1f7b9d5c9c75be62676feeeb91d2e896c5ea/beautifulsoup4-4.7.1-py2-none-any.whl
Collecting pytest (from dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/b3/eb/df264c0b1ff4aaf263375dc09aabd9093364f66060be9b26f3a2c166d558/pytest-4.6.3-py2.py3-none-any.whl
Collecting flask-compress (from dash>=0.38.0->-r requirements.txt (line 2))
Collecting percy (from dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/d6/39/528e689e21baa4d625cecc326c0d56c976d63855f9d114c07ccaed8a73eb/percy-2.0.2-py2.py3-none-any.whl
Collecting dash-core-components==1.0.0 (from dash>=0.38.0->-r requirements.txt (line 2))
Collecting dash-html-components==1.0.0 (from dash>=0.38.0->-r requirements.txt (line 2))
Collecting Flask>=0.12 (from dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/9a/74/670ae9737d14114753b8c8fdf2e8bd212a05d3b361ab15b44937dfd40985/Flask-1.0.3-py2.py3-none-any.whl
Collecting requests[security] (from dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting plotly (from dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/ff/75/3982bac5076d0ce6d23103c03840fcaec90c533409f9d82c19f54512a38a/plotly-3.10.0-py2.py3-none-any.whl
Collecting selenium (from dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/80/d6/4294f0b4bce4de0abf13e17190289f9d0613b0a44e5dd6a7f5ca98459853/selenium-3.141.0-py2.py3-none-any.whl
Collecting pytest-mock (from dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/30/43/8deecb4c123bbc16d25666f1a6d241109c97aeb2e50806b952661c8e4b95/pytest_mock-1.10.4-py2.py3-none-any.whl
Collecting dash-renderer==1.0.0 (from dash>=0.38.0->-r requirements.txt (line 2))
Collecting dash-table==4.0.0 (from dash>=0.38.0->-r requirements.txt (line 2))
Collecting termcolor>=1.1.0 (from pytest-sugar->dash>=0.38.0->-r requirements.txt (line 2))
Collecting packaging>=14.1 (from pytest-sugar->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/91/32/58bc30e646e55eab8b21abf89e353f59c0cc02c417e42929f4a9546e1b1d/packaging-19.0-py2.py3-none-any.whl
Collecting soupsieve>=1.2 (from beautifulsoup4->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/35/e3/25079e8911085ab76a6f2facae0771078260c930216ab0b0c44dc5c9bf31/soupsieve-1.9.2-py2.py3-none-any.whl
Collecting funcsigs>=1.0; python_version < "3.0" (from pytest->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/69/cb/f5be453359271714c01b9bd06126eaf2e368f1fddfff30818754b5ac2328/funcsigs-1.0.2-py2.py3-none-any.whl
Collecting importlib-metadata>=0.12 (from pytest->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/bd/23/dce4879ec58acf3959580bfe769926ed8198727250c5e395e6785c764a02/importlib_metadata-0.18-py2.py3-none-any.whl
Collecting six>=1.10.0 (from pytest->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting attrs>=17.4.0 (from pytest->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/23/96/d828354fa2dbdf216eaa7b7de0db692f12c234f7ef888cc14980ef40d1d2/attrs-19.1.0-py2.py3-none-any.whl
Collecting pluggy<1.0,>=0.12 (from pytest->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/06/ee/de89e0582276e3551df3110088bf20844de2b0e7df2748406876cc78e021/pluggy-0.12.0-py2.py3-none-any.whl
Collecting pathlib2>=2.2.0; python_version < "3.6" (from pytest->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/67/c6/4dbf5dfdbe1140cadf765c3896acc098578626c35721bc7d3eb35f6a8fc1/pathlib2-2.3.4-py2.py3-none-any.whl
Collecting py>=1.5.0 (from pytest->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/76/bc/394ad449851729244a97857ee14d7cba61ddb268dce3db538ba2f2ba1f0f/py-1.8.0-py2.py3-none-any.whl
Collecting atomicwrites>=1.0 (from pytest->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/52/90/6155aa926f43f2b2a22b01be7241be3bfd1ceaf7d0b3267213e8127d41f4/atomicwrites-1.3.0-py2.py3-none-any.whl
Collecting wcwidth (from pytest->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
Collecting colorama; sys_platform == "win32" (from pytest->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
Collecting more-itertools<6.0.0,>=4.0.0; python_version <= "2.7" (from pytest->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/2f/9d/dcfe59e213093695f108508af1214cf9cd95cc5489e46877ec5cb56369e5/more_itertools-5.0.0-py2-none-any.whl
Collecting click>=5.1 (from Flask>=0.12->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
Collecting Werkzeug>=0.14 (from Flask>=0.12->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/9f/57/92a497e38161ce40606c27a86759c6b92dd34fcdb33f64171ec559257c02/Werkzeug-0.15.4-py2.py3-none-any.whl
Collecting Jinja2>=2.10 (from Flask>=0.12->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/1d/e7/fd8b501e7a6dfe492a433deb7b9d833d39ca74916fa8bc63dd1a4947a671/Jinja2-2.10.1-py2.py3-none-any.whl
Collecting itsdangerous>=0.24 (from Flask>=0.12->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/76/ae/44b03b253d6fade317f32c24d100b3b35c2239807046a4c953c7b89fa49e/itsdangerous-1.1.0-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests[security]->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/69/1b/b853c7a9d4f6a6d00749e94eb6f3a041e342a885b87340b79c1ef73e3a78/certifi-2019.6.16-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests[security]->dash>=0.38.0->-r requirements.txt (line 2))  Using cached https://files.pythonhosted.org/packages/e6/60/247f23a7121ae632d62811ba7f273d0e58972d75e58a94d329d51550a47d/urllib3-1.25.3-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests[security]->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests[security]->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting cryptography>=1.3.4; extra == "security" (from requests[security]->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/d8/30/6313af106e5abff8bfa78eb2ce630673bb5add4fafd3b28d4bd0271c8e7f/cryptography-2.7-cp27-cp27m-win_amd64.whl
Collecting pyOpenSSL>=0.14; extra == "security" (from requests[security]->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/01/c8/ceb170d81bd3941cbeb9940fc6cc2ef2ca4288d0ca8929ea4db5905d904d/pyOpenSSL-19.0.0-py2.py3-none-any.whl
Collecting nbformat>=4.2 (from plotly->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/da/27/9a654d2b6cc1eaa517d1c5a4405166c7f6d72f04f6e7eea41855fe808a46/nbformat-4.4.0-py2.py3-none-any.whl
Collecting pytz (from plotly->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/3d/73/fe30c2daaaa0713420d0382b16fbb761409f532c56bdcc514bf7b6262bb6/pytz-2019.1-py2.py3-none-any.whl
Collecting decorator>=4.0.6 (from plotly->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/5f/88/0075e461560a1e750a0dcbf77f1d9de775028c37a19a346a6c565a257399/decorator-4.4.0-py2.py3-none-any.whl
Collecting retrying>=1.3.3 (from plotly->dash>=0.38.0->-r requirements.txt (line 2))
Collecting mock; python_version < "3.0" (from pytest-mock->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/05/d2/f94e68be6b17f46d2c353564da56e6fb89ef09faeeff3313a046cb810ca9/mock-3.0.5-py2.py3-none-any.whl
Collecting pyparsing>=2.0.2 (from packaging>=14.1->pytest-sugar->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/dd/d9/3ec19e966301a6e25769976999bd7bbe552016f0d32b577dc9d63d2e0c49/pyparsing-2.4.0-py2.py3-none-any.whl
Collecting backports.functools-lru-cache; python_version < "3" (from soupsieve>=1.2->beautifulsoup4->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/03/8e/2424c0e65c4a066e28f539364deee49b6451f8fcd4f718fefa50cc3dcf48/backports.functools_lru_cache-1.5-py2.py3-none-any.whl
Collecting zipp>=0.5 (from importlib-metadata>=0.12->pytest->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/a0/0f/9bf71d438d2e9d5fd0e4569ea4d1a2b6f5a524c234c6d221b494298bb4d1/zipp-0.5.1-py2.py3-none-any.whl
Collecting contextlib2; python_version < "3" (from importlib-metadata>=0.12->pytest->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/a2/71/8273a7eeed0aff6a854237ab5453bc9aa67deb49df4832801c21f0ff3782/contextlib2-0.5.5-py2.py3-none-any.whl
Collecting configparser>=3.5; python_version < "3" (from importlib-metadata>=0.12->pytest->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/ba/05/6c96328e92e625fc31445d24d75a2c92ef9ba34fc5b037fe69693c362a0d/configparser-3.7.4-py2.py3-none-any.whl
Collecting scandir; python_version < "3.5" (from pathlib2>=2.2.0; python_version < "3.6"->pytest->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/f9/d0/6b7b38eaf9964510f5c32aa5aaf9f419864d2e0ebe34274e6cba5689a0c5/scandir-1.10.0-cp27-cp27m-win_amd64.whl
Collecting MarkupSafe>=0.23 (from Jinja2>=2.10->Flask>=0.12->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/f7/58/85258115ce58190f20c28fbb3b91c3b1a0a42e6375b100e489427c30488a/MarkupSafe-1.1.1-cp27-cp27m-win_amd64.whl
Collecting enum34; python_version < "3" (from cryptography>=1.3.4; extra == "security"->requests[security]->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting asn1crypto>=0.21.0 (from cryptography>=1.3.4; extra == "security"->requests[security]->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/ea/cd/35485615f45f30a510576f1a56d1e0a7ad7bd8ab5ed7cdc600ef7cd06222/asn1crypto-0.24.0-py2.py3-none-any.whl
Collecting ipaddress; python_version < "3" (from cryptography>=1.3.4; extra == "security"->requests[security]->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/fc/d0/7fc3a811e011d4b388be48a0e381db8d990042df54aa4ef4599a31d39853/ipaddress-1.0.22-py2.py3-none-any.whl
Collecting cffi!=1.11.3,>=1.8 (from cryptography>=1.3.4; extra == "security"->requests[security]->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/fa/24/37ec704b98ffc36e7d0ade9e4653539c0b8e6fec34f084f30194609aa10b/cffi-1.12.3-cp27-cp27m-win_amd64.whl
Collecting traitlets>=4.1 (from nbformat>=4.2->plotly->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/93/d6/abcb22de61d78e2fc3959c964628a5771e47e7cc60d53e9342e21ed6cc9a/traitlets-4.3.2-py2.py3-none-any.whl
Collecting jupyter-core (from nbformat>=4.2->plotly->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/e6/25/6ffb0f6e57fa6ef5d2f814377133b361b42a6dd39105f4885a4f1666c2c3/jupyter_core-4.5.0-py2.py3-none-any.whl
Collecting jsonschema!=2.5.0,>=2.4 (from nbformat>=4.2->plotly->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/aa/69/df679dfbdd051568b53c38ec8152a3ab6bc533434fc7ed11ab034bf5e82f/jsonschema-3.0.1-py2.py3-none-any.whl
Collecting ipython-genutils (from nbformat>=4.2->plotly->dash>=0.38.0->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/fa/bc/9bd3b5c2b4774d5f33b2d544f1460be9df7df2fe42f352135381c347c69a/ipython_genutils-0.2.0-py2.py3-none-any.whl
Collecting pycparser (from cffi!=1.11.3,>=1.8->cryptography>=1.3.4; extra == "security"->requests[security]->dash>=0.38.0->-r requirements.txt (line 2))
Collecting pyrsistent>=0.14.0 (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2->plotly->dash>=0.38.0->-r requirements.txt (line 2))
Collecting functools32; python_version < "3" (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2->plotly->dash>=0.38.0->-r requirements.txt (line 2))
Requirement already satisfied: setuptools in c:\users\zianhu\pycharmprojects\my_dash_component\venv\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2->plotly->dash>=0.38.0->-r requirements.txt (line 2)) (41.0.1)
Installing collected packages: lxml, termcolor, pyparsing, six, packaging, funcsigs, zipp, contextlib2, scandir, pathlib2, configparser, importlib-metadata, attrs, pluggy, py, atomicwrites, wcwidth, colorama, more-itertools, pytest, pytest-sugar, waitress, backports.functools-lru-cache, soupsieve, beautifulsoup4, click, Werkzeug, MarkupSafe, Jinja2, itsdangerous, Flask, flask-compress, certifi, urllib3, idna, chardet, enum34, asn1crypto, ipaddress, pycparser, cffi, cryptography, pyOpenSSL, requests, percy, dash-core-components, dash-html-components, decorator, ipython-genutils, traitlets, jupyter-core, pyrsistent, functools32, jsonschema, nbformat, pytz, retrying, plotly, selenium, mock, pytest-mock, dash-renderer, dash-table, dash
Successfully installed Flask-1.0.3 Jinja2-2.10.1 MarkupSafe-1.1.1 Werkzeug-0.15.4 asn1crypto-0.24.0 atomicwrites-1.3.0 attrs-19.1.0 backports.functools-lru-cache-1.5 beautifulsoup4-4.7.1 certifi-2019.6.16 cffi-1.12.3 chardet-3.0.4 click-7.0 colorama-0.4.1 configparser-3.7.4 contextlib2-0.5.5 cryptography-2.7 dash-1.0.0 dash-core-components-1.0.0 dash-html-components-1.0.0 dash-renderer-1.0.0 dash-table-4.0.0 decorator-4.4.0 enum34-1.1.6 flask-compress-1.4.0 funcsigs-1.0.2 functools32-3.2.3.post2 idna-2.8 importlib-metadata-0.18 ipaddress-1.0.22 ipython-genutils-0.2.0 itsdangerous-1.1.0 jsonschema-3.0.1 jupyter-core-4.5.0 lxml-4.3.4 mock-3.0.5 more-itertools-5.0.0 nbformat-4.4.0 packaging-19.0 pathlib2-2.3.4 percy-2.0.2 plotly-3.10.0 pluggy-0.12.0 py-1.8.0 pyOpenSSL-19.0.0 pycparser-2.19 pyparsing-2.4.0 pyrsistent-0.15.2 pytest-4.6.3 pytest-mock-1.10.4 pytest-sugar-0.9.2 pytz-2019.1 requests-2.22.0 retrying-1.3.3 scandir-1.10.0 selenium-3.141.0 six-1.12.0 soupsieve-1.9.2 termcolor-1.1.0 traitlets-4.3.2 urllib3-1.25.3 waitress-1.3.0 wcwidth-0.1.7 zipp-0.5.1
Executing: npm install --ignore-scripts
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
npm WARN rollback Rolling back node-pre-gyp@0.12.0 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\Users\zianhu\PycharmProjects\my_dash_component\node_modules\fsevents\node_modules'
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN my_dash_component@0.0.1 No repository field.
npm WARN my_dash_component@0.0.1 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1471 packages from 1262 contributors and audited 21320 packages in 94.614s
found 14 vulnerabilities (1 moderate, 13 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Building initial bundles...
Executing: venv\Scripts\python -m dash.development.component_generator ./src/lib/components my_dash_component
'REQUIRED$' is not recognized as an internal or external command,
operable program or batch file.

Error generating metadata in my_dash_component (status=255)
post_gen_project command failed: venv\Scripts\python -m dash.development.component_generator ./src/lib/components my_dash_component
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)`

**Comment by miqh** [comment]
@Aprilhuu, I just ran into this myself while surveying how to upgrade an existing component boilerplate to use Dash 1.0.0.

I did some digging and I think I found what's causing it.

Part of the Dash component generation process appears to run a script named `extract-meta.js` from another script named `component_generator.py`. Some of the arguments (e.g. ignored file patterns) fed into `extract-meta.js` by default contain carets. On Windows, carets are treated specially when used as part of a command. Consequently, the full command generated by `component_generator.py` has a malformed interpretation.

I've worked around this in the interim by enclosing the pattern-related arguments with quotes. If you want to follow my edit, you can find `component_generator.py` inside `venv\Lib\site-packages\dash`.

https://github.com/plotly/dash/blob/2aca30749bcc60cc47b51639327c0e0f6900539d/dash/development/component_generator.py#L64

The change would look like:

```
"node {} \"{}\" \"{}\" {}".format(
```

I'm happy to submit a patch for this, but I'm not sure if this is the best solution.
