### ISSUE TITLE
Error in installing BoilerPlate

### ISSUE THREAD

**Issue by ChaksUdacity** [plotly/dash-component-boilerplate#81]
Executing: venv/bin/python -m dash.development.component_generator ./src/lib/components examplecomp -p package-info.json --r-prefix 'dc'
Traceback (most recent call last):
  File "/Users/admin/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/admin/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/admin/Desktop/BoilerPlate/examplecomp/venv/lib/python3.6/site-packages/dash/development/component_generator.py", line 14, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
post_gen_project command failed: venv/bin/python -m dash.development.component_generator ./src/lib/components examplecomp -p package-info.json --r-prefix 'dc'
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)

**Comment by pieroliviermarquis** [comment]
I cloned the boilerplate and inlcuded pyaml in the requirements.txt and it fixed that issue.

**Comment by BenMacKenzie** [comment]
this should be an easy fix....

**Comment by foosa** [comment]
> I cloned the boilerplate and inlcuded pyaml in the requirements.txt and it fixed that issue.

Can you specifically tell me what you did?  I cant seem to me able to get this to work.  To those at Plotly -- this is breaking your component boilerplate tool.

**Comment by BenMacKenzie** [comment]
i also had to edit setup.py, the path to package.json is wrong (i.e. it is actually in the same directory as setup.py).

**Comment by ghavranek** [comment]
I added pyaml to the requirement.txt file.  But, when I look at the setup.py file it looks as if the path is correct?   `with open(os.path.join('{{cookiecutter.project_shortname}}', 'package.json')) as f:
    package = json.load(f)` 

The error I am receiving now is:  
Executing: venv\Scripts\python -m dash.development.component_generator ./src/lib/components example_component
'REQUIRED$' is not recognized as an internal or external command,
operable program or batch file.I am now receiving an

**Comment by ghavranek** [comment]
> @foosa 

> Can you specifically tell me what you did? I cant seem to me able to get this to work. To those at Plotly -- this is breaking your component boilerplate tool.

Fork the repository and then edit:  /dash-component-boilerplate/{{cookiecutter.project_shortname}}/requirements.txt 

![image](https://user-images.githubusercontent.com/12696562/65047831-1fb39b00-d931-11e9-9031-ff3bea4a89b1.png)

Alternatively, you can use cookiecutter with my repository:  

`cookiecutter https://github.com/ghavranek/dash-component-boilerplate`

As I referenced above though, there still appears to be an issue with Windows.

**Comment by ishto7** [comment]
This worked out for me on Windows. Thanks @ghavranek

**Comment by alexcjohnson** [comment]
Merged #86 to fix the yaml dep with the newer dash install syntax. #78 will fix the package.json path, I'll leave this issue open until that gets merged.

**Comment by alexcjohnson** [comment]
Thanks all - closing, as #78 addressed the pieces unique to this issue. #87 should fix the windows problem by bringing in the latest `dash` including the fix from @stevej2608
