### ISSUE TITLE
Should this be a cookiecutter?

### ISSUE THREAD

**Issue by kmader** [plotly/dash-component-boilerplate#9]
Cookiecutter might make it a bit easier to for getting a project setup correctly?
https://cookiecutter.readthedocs.io/en/latest/

**Comment by kmader** [comment]
It works really well for the JupyterWidgets (https://github.com/jupyter-widgets/widget-ts-cookiecutter) which have very similar complex python+js setups. It also gives you the opportunity to quasi-force CI/testing for both languages in a sensible manner.

**Comment by T4rk1n** [comment]
@kmader 
I tried cookiecutter and I am convinced it is the good choice. I think I can even call it from py so I can integrate it with the cli if we want the command to be something like `dash create-component`.

**Comment by bpostlethwaite** [comment]
Thanks for the pointer @kmader !!
