### ISSUE TITLE
Uncaught SyntaxError: Unexpected token ':'

### ISSUE THREAD

**Issue by westonkjones** [plotly/dash-component-boilerplate#95]
Sorry if this has been posted before, or is a dumb question! I did a search for this issue, but came up empty.

I am trying to just write a dash wrapper for an existing react component. It mostly works as expected, however some of the functionality is silently failing. Opening the console I am greeted with the following error

![image](https://user-images.githubusercontent.com/4962051/68918761-34e05680-0735-11ea-8407-518c31fe04bd.png)

The component works as expected when running a react version using `npm run start`

**Comment by eric-burel** [comment]
Same here, the minimap does not seem to have a valid format. It seems to happen when a map file is imported by mistake.
https://github.com/Microsoft/TypeScript/issues/5649

**Comment by westonkjones** [comment]
> Same here, the minimap does not seem to have a valid format. It seems to happen when a map file is imported by mistake.
> [microsoft/TypeScript#5649](https://github.com/microsoft/TypeScript/issues/5649)
> 
> It is indeed add to the page footer.

Oh, great find! I didn't even notice before that it was the source map. As a temporary fix I was able to disable remove it from the generated `_js_dist` in the `__init__.py` of the build. This actually didn't solve my original issue, unfortunately
